version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
    
  db2:
     image: mysql
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       
       MYSQL_USER: bruno
       MYSQL_PASSWORD: rut
       MYSQL_ROOT_PASSWORD: example
       MYSQL_DATABASE: phpapi
     ports:
      - 3306:3306

      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080